name: Linter CI
on:
    # Run on pull requests
    pull_request:
        branches: [master, main, dev]
    
    # Run on push to master
    push:
        branches: [master, main, dev]

jobs:
    lint-spawn:
        name: Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              uses: super-linter/super-linter@v5
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: /
                  JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
                  VALIDATE_JAVASCRIPT_ES: true